spring:
  data:
    redis:
      host: localhost
      port: 6379
      # Timeout should be short for test
      timeout: 1000ms

  datasource:
    # Use H2 in-memory database for testing
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

aws:
  region: us-east-1
  local-stack:
    enable: false
    endpoint: http://localhost:4566

# Disable external APIs for test
external-apis:
  user-management:
    base-url: http://localhost:8081
  fidc-permission:
    base-url: http://localhost:8082

feign:
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 2000
        retry-attempts: 1

# JWT configuration
jwt:
  fallback-secret: test-fallback-secret-key

# Security configuration - TESTE: localhost HABILITADO
app:
  security:
    allow-localhost: true

properties:
  session:
    ttl-minutes: 30
    cleanup-interval-minutes: 5
    secret-length: 36

logging:
  level:
    root: INFO
    com.banco.fidc.auth: DEBUG