spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fidc_auth_db}
    username: ${DATABASE_USER:fidc_auth_user}
    password: ${DATABASE_PASSWORD:senha123}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

aws:
  region: ${AWS_REGION:us-east-1}
  secret-manager:
    jwt:
      name: ${JWT_SECRET_NAME:dev/jwt/secret}

external-apis:
  user-management:
    base-url: ${USER_MANAGEMENT_URL:http://user-management-dev.internal:8080}
  fidc-permission:
    base-url: ${FIDC_PERMISSION_URL:http://fidc-permission-dev.internal:8080}

feign:
  client:
    config:
      default:
        connect-timeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        read-timeout: ${FEIGN_READ_TIMEOUT:10000}
        retry-attempts: ${FEIGN_RETRY_ATTEMPTS:3}
        logger-level: basic

# JWT configuration
jwt:
  fallback-secret: ${JWT_FALLBACK_SECRET:dev-fallback-secret-key}

# Security configuration
app:
  security:
    allow-localhost: ${ALLOW_LOCALHOST:true}

properties:
  session:
    ttl-minutes: ${SESSION_TTL_MINUTES:30}
    cleanup-interval-minutes: ${SESSION_CLEANUP_INTERVAL_MINUTES:5}
    secret-length: ${SESSION_SECRET_LENGTH:36}