application:
  name: fidc-auth
  squad: acesso-seguranca
  version: $VERSION
  base_deploy_image: 21-alpine3.18-jre
  base_build_image: 21-alpine3.18-jdk

infra:
  env:
    name: uat
    javaOpts: -Denv.type=uat -XX:+UseG1GC -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=75.0

  deploy:
    maxSurge: 50%
    maxUnavailable: 0
    terminationGracePeriodSeconds: 135

    resources:
      requests:
        cpu: 400m
        memory: 1Gi
      limits:
        memory: 1.5Gi

    healthcheck:
      path: /public/actuator/health

      livenessProbe:
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 10
        failureThreshold: 5

      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 10
        failureThreshold: 3

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70

  ingress:
    path: /fidc-auth
    class: nginx-internal

  armArch: true

  dockerfile:
    custom_steps: ''
    custom_entrypoint: 'application/build/distributions/application-0.0.1-SNAPSHOT.tar'

observability:
  enabled: false